In [1]:
import numpy as np
import pandas as pd

In [2]:
df_test = pd.read_csv('test.csv')
df_train = pd.read_csv('train.csv')

In [4]:
pd.concat([df_train, df_test])

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,NaN
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,NaN
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,NaN
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,NaN
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,NaN

In [8]:
emp1 = pd.DataFrame({
    "id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Anurag", "Rahul", "Priya", "Sneha", "Amit",
             "Neha", "Rohit", "Pooja", "Vikas", "Karan"],
    "sal": [55000, 62000, 48000, 70000, 52000,
            65000, 58000, 45000, 75000, 60000],
    "dept": ["IT", "HR", "IT", "Finance", "Sales",
             "IT", "HR", "Sales", "Finance", "IT"],
    "manager": ["Raj", "Meena", "Raj", "Suresh", "Vijay",
                "Raj", "Meena", "Vijay", "Suresh", "Raj"],
    "loc": ["Pune", "Mumbai", "Pune", "Delhi", "Bangalore",
            "Hyderabad", "Mumbai", "Pune", "Delhi", "Hyderabad"]
})
emp1

    id    name    sal     dept manager        loc
0  101  Anurag  55000       IT     Raj       Pune
1  102   Rahul  62000       HR   Meena     Mumbai
2  103   Priya  48000       IT     Raj       Pune
3  104   Sneha  70000  Finance  Suresh      Delhi
4  105    Amit  52000    Sales   Vijay  Bangalore
5  106    Neha  65000       IT     Raj  Hyderabad
6  107   Rohit  58000       HR   Meena     Mumbai
7  108   Pooja  45000    Sales   Vijay       Pune
8  109   Vikas  75000  Finance  Suresh      Delhi
9  110   Karan  60000       IT     Raj  Hyderabad

In [19]:
emp2 = pd.DataFrame({
    "name": ["Anurag", "Rahul","Priya", "Sneha", "Amit",
             "Neha", "Rohit", "Pooja", "Vikas", "Karan"],
    "dept": ["IT", "HR", "IT", "Finance", "Sales",
             "IT", "HR", "Sales", "Finance", "IT"],
    "team_name": ["Backend", "Recruitment", "Testing", "Accounts", "Retail",
                   "Data", "Recruitment", "Retail", "Audit", "Backend"],
    "role": ["Developer", "HR Executive", "Tester", "Accountant", "Sales Executive",
             "Data Analyst", "HR Executive", "Sales Executive", "Auditor", "Developer"]
})

emp2

     name     dept    team_name             role
0  Anurag       IT      Backend        Developer
1   Rahul       HR  Recruitment     HR Executive
2   Priya       IT      Testing           Tester
3   Sneha  Finance     Accounts       Accountant
4    Amit    Sales       Retail  Sales Executive
5    Neha       IT         Data     Data Analyst
6   Rohit       HR  Recruitment     HR Executive
7   Pooja    Sales       Retail  Sales Executive
8   Vikas  Finance        Audit          Auditor
9   Karan       IT      Backend        Developer

In [20]:
pd.concat([emp1, emp2], axis=1)

,id,name,sal,dept,manager,loc,name,dept,team_name,role
0,101,Anurag,55000,IT,Raj,Pune,Anurag,IT,Backend,Developer
1,102,Rahul,62000,HR,Meena,Mumbai,Rahul,HR,Recruitment,HR Executive
2,103,Priya,48000,IT,Raj,Pune,Priya,IT,Testing,Tester
3,104,Sneha,70000,Finance,Suresh,Delhi,Sneha,Finance,Accounts,Accountant
4,105,Amit,52000,Sales,Vijay,Bangalore,Amit,Sales,Retail,Sales Executive
5,106,Neha,65000,IT,Raj,Hyderabad,Neha,IT,Data,Data Analyst
6,107,Rohit,58000,HR,Meena,Mumbai,Rohit,HR,Recruitment,HR Executive
7,108,Pooja,45000,Sales,Vijay,Pune,Pooja,Sales,Retail,Sales Executive
8,109,Vikas,75000,Finance,Suresh,Delhi,Vikas,Finance,Audit,Auditor
9,110,Karan,60000,IT,Raj,Hyderabad,Karan,IT,Backend,Developer

## Join

In [22]:
pd.merge(emp1, emp2, on=['name', 'dept'])
pd.merge(emp1, emp2, on='name')

,id,name,sal,dept_x,manager,loc,dept_y,team_name,role
0,101,Anurag,55000,IT,Raj,Pune,IT,Backend,Developer
1,102,Rahul,62000,HR,Meena,Mumbai,HR,Recruitment,HR Executive
2,103,Priya,48000,IT,Raj,Pune,IT,Testing,Tester
3,104,Sneha,70000,Finance,Suresh,Delhi,Finance,Accounts,Accountant
4,105,Amit,52000,Sales,Vijay,Bangalore,Sales,Retail,Sales Executive
5,106,Neha,65000,IT,Raj,Hyderabad,IT,Data,Data Analyst
6,107,Rohit,58000,HR,Meena,Mumbai,HR,Recruitment,HR Executive
7,108,Pooja,45000,Sales,Vijay,Pune,Sales,Retail,Sales Executive
8,109,Vikas,75000,Finance,Suresh,Delhi,Finance,Audit,Auditor
9,110,Karan,60000,IT,Raj,Hyderabad,IT,Backend,Developer

In [27]:
pd.merge(emp2, emp1,on='name', how='left')

,name,dept_x,team_name,role,id,sal,dept_y,manager,loc
0,Anurag,IT,Backend,Developer,101,55000,IT,Raj,Pune
1,Rahul,HR,Recruitment,HR Executive,102,62000,HR,Meena,Mumbai
2,Priya,IT,Testing,Tester,103,48000,IT,Raj,Pune
3,Sneha,Finance,Accounts,Accountant,104,70000,Finance,Suresh,Delhi
4,Amit,Sales,Retail,Sales Executive,105,52000,Sales,Vijay,Bangalore
5,Neha,IT,Data,Data Analyst,106,65000,IT,Raj,Hyderabad
6,Rohit,HR,Recruitment,HR Executive,107,58000,HR,Meena,Mumbai
7,Pooja,Sales,Retail,Sales Executive,108,45000,Sales,Vijay,Pune
8,Vikas,Finance,Audit,Auditor,109,75000,Finance,Suresh,Delhi
9,Karan,IT,Backend,Developer,110,60000,IT,Raj,Hyderabad

In [31]:
dept = pd.DataFrame({
    "deptno": [10, 20, 30, 40],
    "dname": ["ACCOUNTING", "RESEARCH", "SALES", "OPERATIONS"],
    "loc": ["NEW YORK", "DALLAS", "CHICAGO", "BOSTON"]
})

emp = pd.DataFrame({
    "empno": [7369, 7499, 7521, 7566, 7654,
              7698, 7782, 7788, 7839, 7934],
    
    "ename": ["SMITH", "ALLEN", "WARD", "JONES", "MARTIN",
              "BLAKE", "CLARK", "SCOTT", "KING", "MILLER"],
    
    "sal": [800, 1600, 1250, 2975, 1250,
            2850, 2450, 3000, 5000, 1300],
    
    "deptno": [20, 30, 30, 20, 30,
               30, 10, 20, 10, 10]
})

In [37]:
pd.merge(emp, dept, how='cross')
pd.merge(emp, dept, how='left')
pd.merge(emp, dept, how='right')
pd.merge(emp, dept, how='outer')
pd.merge(dept,emp, how='inner')

   deptno       dname       loc  empno   ename   sal
0      10  ACCOUNTING  NEW YORK   7782   CLARK  2450
1      10  ACCOUNTING  NEW YORK   7839    KING  5000
2      10  ACCOUNTING  NEW YORK   7934  MILLER  1300
3      20    RESEARCH    DALLAS   7369   SMITH   800
4      20    RESEARCH    DALLAS   7566   JONES  2975
5      20    RESEARCH    DALLAS   7788   SCOTT  3000
6      30       SALES   CHICAGO   7499   ALLEN  1600
7      30       SALES   CHICAGO   7521    WARD  1250
8      30       SALES   CHICAGO   7654  MARTIN  1250
9      30       SALES   CHICAGO   7698   BLAKE  2850

In [40]:
imdb = pd.read_csv(r'..\4 groupby\imdb_top_1000.csv')

In [ ]:
pd

ValueError: 2 columns passed, passed data had 1000 columns