In [1]:
import numpy as np
import pandas as pd

In [2]:
ipl = pd.read_csv('ipl.csv')

## Attributes of DataFrame

#### size <hr>

In [3]:
ipl.size

32318

#### dtypes<hr>

In [41]:
ipl.dtypes

date                 str
season               str
city                 str
venue                str
team1                str
team2                str
toss_winner          str
toss_decision        str
team1_runs         int64
team1_wickets      int64
team2_runs         int64
team2_wickets      int64
winner               str
result_type          str
win_by_runs        int64
win_by_wickets     int64
player_of_match      str
match_referee        str
umpire1              str
umpire2              str
tv_umpire            str
reserve_umpire       str
overs_limit        int64
team1_players        str
team2_players        str
year               int64
dtype: object

#### shape<hr>

In [9]:
ipl.shape

(1243, 26)

#### values<hr>

In [11]:
ipl.values

array([['2008-04-18', '2007/08', 'Bangalore', ...,
        'R Dravid, W Jaffer, V Kohli, JH Kallis, CL White, MV Boucher, B Akhil, AA Noffke, P Kumar, Z Khan, SB Joshi',
        'SC Ganguly, BB McCullum, RT Ponting, DJ Hussey, Mohammad Hafeez, LR Shukla, WP Saha, AB Agarkar, AB Dinda, M Kartik, I Sharma',
        2008],
       ['2008-04-19', '2007/08', 'Chandigarh', ...,
        'K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh, SM Katich, IK Pathan, P Dharmani, B Lee, PP Chawla, WA Mota, S Sreesanth',
        'PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK Raina, JDP Oram, S Badrinath, Joginder Sharma, P Amarnath, MS Gony, M Muralitharan',
        2008],
       ['2008-04-19', '2007/08', 'Delhi', ...,
        'G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD Karthik, R Bhatia, M Manhas, DL Vettori, MF Maharoof, B Geeves, GD McGrath',
        'T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehmann, RA Jadeja, M Rawat, D Salunkhe, SK Warne, SK Trivedi, MM Patel',
        2008],
       ...,
       ['2026-05-27', '2026', 'New Chandigarh', ...,
        'YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Parag, D Ferreira, MD Shanaka, RA Jadeja, JC Archer, N Burger, SS Mishra, Brijesh Sharma, Yash Raj Punja',
        'PP Hinge, Abhishek Sharma, TM Head, Ishan Kishan, R Smaran, H Klaasen, Nithish Kumar Reddy, Salil Arora, PJ Cummins, Shivang Kumar, E Malinga, Sakib Hussain',
        2026],
       ['2026-05-29', '2026', 'New Chandigarh', ...,
        'TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhruv Jurel, RA Jadeja, R Parag, MD Shanaka, JC Archer, D Ferreira, N Burger, Brijesh Sharma, Yash Raj Punja',
        'Mohammed Siraj, B Sai Sudharsan, Shubman Gill, JC Buttler, Washington Sundar, R Tewatia, JO Holder, N Sindhu, Rashid Khan, R Sai Kishore, K Rabada, M Prasidh Krishna',
        2026],
       ['2026-05-31', '2026', 'Ahmedabad', ...,
        'M Prasidh Krishna, B Sai Sudharsan, Shubman Gill, N Sindhu, JC Buttler, Washington Sundar, Arshad Khan, R Tewatia, JO Holder, Rashid Khan, K Rabada, Mohammed Siraj',
        'JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Patidar, KH Pandya, TH David, JM Sharma, R Shepherd, B Kumar, JR Hazlewood, Rasikh Salam',
        2026]], shape=(1243, 26), dtype=object)

#### index<hr>

In [12]:
ipl.index

RangeIndex(start=0, stop=1243, step=1)

In [26]:
a = pd.DataFrame({'math': [90,70,80,88],
                  'english':[56,70,86,45]})
a.index = ['Harsh', 'Rasika', 'Jay', 'Viraj']
a.index = ['Nikita', 'Rasika Hajare', 'Peter', 'Ritanshu']
x = list(a.index)
x[0] = 'Nikita Nikam'
a.index = x
a

               math  english
Nikita Nikam     90       56
Rasika Hajare    70       70
Peter            80       86
Ritanshu         88       45

#### columns <hr>

In [28]:
ipl.columns

Index(['date', 'season', 'city', 'venue', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'team1_runs', 'team1_wickets', 'team2_runs',
       'team2_wickets', 'winner', 'result_type', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'match_referee', 'umpire1',
       'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players', 'year'],
      dtype='str')

In [31]:
a.columns = ['English', 'History']
a

               English  History
Nikita Nikam        90       56
Rasika Hajare       70       70
Peter               80       86
Ritanshu            88       45

In [42]:
movies = pd.read_csv('bollywood.csv')

## Methods of DataFrame

#### head <hr>

In [ ]:
movies.head() # first 5 rows
ipl.head(3)

                                  movie              lead
0              Uri: The Surgical Strike     Vicky Kaushal
1                         Battalion 609       Vicky Ahuja
2  The Accidental Prime Minister (film)       Anupam Kher
3                       Why Cheat India     Emraan Hashmi
4                       Evening Shadows  Mona Ambegaonkar

#### tail<hr>

In [47]:
ipl.tail() #last 5 rows
movies.tail(7)

                         movie              lead
1493  Devdas (2002 Hindi film)    Shah Rukh Khan
1494                    Kaante  Amitabh Bachchan
1495    Hum Tumhare Hain Sanam    Shah Rukh Khan
1496       Aankhen (2002 film)  Amitabh Bachchan
1497           Saathiya (film)      Vivek Oberoi
1498            Company (film)        Ajay Devgn
1499      Awara Paagal Deewana      Akshay Kumar

#### sample<hr>

In [59]:
ipl.sample() # a random row
ipl.sample(3) # 3 random row

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,year
783,2020-10-12,2020/21,Unknown,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,bat,194,2,...,AB de Villiers,V Narayan Kutty,RK Illingworth,K Srinivasan,KN Ananthapadmanabhan,VA Kulkarni,20,"AJ Finch, D Padikkal, V Kohli, AB de Villiers,...","T Banton, Shubman Gill, N Rana, EJG Morgan, KD...",2020
85,2009-05-05,2009,Durban,Kingsmead,Delhi Daredevils,Kolkata Knight Riders,Kolkata Knight Riders,bat,157,1,...,G Gambhir,J Srinath,GAV Baxter,IL Howell,S Ravi,KH Hurter,20,"G Gambhir, DA Warner, TM Dilshan, AB de Villie...","MN van Wyk, BB McCullum, BJ Hodge, MC Henrique...",2009
49,2008-05-25,2007/08,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Royal Challengers Bangalore,Deccan Chargers,bat,165,10,...,R Vinay Kumar,Talat Ali,Asad Rauf,RE Koertzen,GA Pratapkumar,Unknown,20,"AC Gilchrist, HH Gibbs, RG Sharma, LPC Silva, ...","JH Kallis, W Jaffer, Misbah-ul-Haq, R Dravid, ...",2008

#### set_index<hr>
`syntax : variable.set_index(column_name)`

In [69]:
japan  = pd.read_csv('japan_birth_statistics_1899_2023.csv')
japan.set_index('year')  # this will not change the original df

,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
year,,,,,,
2023,727288,372603,354685,6.0,105.1,1.20
2022,770759,395257,375502,6.3,105.3,1.26
2021,811622,415903,395719,6.6,105.1,1.30
2020,840835,430713,410122,6.8,105.0,1.33
2019,865239,443430,421809,7.0,105.1,1.36
...,...,...,...,...,...,...
1903,1489816,763806,726010,32.7,105.2,NaN
1902,1510835,773296,737539,33.6,104.8,NaN
1901,1501591,769494,732097,33.9,105.1,NaN
1900,1420534,727916,692618,32.4,105.1,NaN
1899,1386981,713442,673539,32.0,105.9,NaN

In [70]:
japan.head(1)

,year,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
0,2023,727288,372603,354685,6.0,105.1,1.2

`syntax : variable.set_index(column_name, inplace = True)`

In [71]:
japan.set_index('year',inplace=True)

In [72]:
japan.head(1)

,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
year,,,,,,
2023,727288,372603,354685,6.0,105.1,1.2